spring:
  application:
    name: Library
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=LibraryDB
    username: syssa
    password: suquele123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2019Dialect




server:
  port: 0 # UP random port

# On which server will I register
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
